INSERT INTO SERIES_FAVORITAS VALUES
  (SEQ_SERIES_FAVORITAS.NEXTVAL, 1, 'FULANO', 1, 'GOT', 5);
  
  INSERT INTO COMENTARIO VALUES
  (SEQ_COMENTARIO.NEXTVAL, 1, 'FULANO', 1, 'GOT', 'SHOW DE BOLA!!!!');